
set TOPDIR=%~dp0

g++.exe -c -o %TOPDIR%main.o %TOPDIR%main.cpp -std=c++03 -O3 -DNDEBUG  -DMCL_DONT_USE_OPENSSL -DMCL_SIZEOF_UNIT=8 -DMCL_MAX_BIT_SIZE=384 -DCYBOZU_DONT_USE_EXCEPTION -DCYBOZU_DONT_USE_STRING -I %TOPDIR%/include -I %TOPDIR%/mcl/include -DBLS_ETH=1 -DWINDOWS_DEFINE -DMCL_BINT_ASM=0

g++.exe -o %TOPDIR%test.exe %TOPDIR%main.o -L%TOPDIR%win/lib -lbls384_256